# Generated by Django 5.2.10 on 2026-02-03 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='consent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата согласия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПДН'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Браузер пользователя', verbose_name='User-Agent'),
        ),
    ]
