# Generated by Django 5.2.10 on 2026-02-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contactrequest_consent_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_phone_2',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='npo.arsenal.info@mail.ru', max_length=254, verbose_name='Email для связи'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='8-960-283-15-14', max_length=30, verbose_name='Телефон'),
        ),
    ]
