# Generated by Django 5.2.10 on 2026-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_remove_phone2_update_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='turret_image',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию турели для отображения в секции "О системе"', null=True, upload_to='turret/', verbose_name='Изображение турели'),
        ),
    ]
