# Generated by Django 5.2.10 on 2026-02-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_add_turret_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В разработке'), ('completed', 'Реализовано')], default='planned', max_length=20, verbose_name='Статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'План развития',
                'verbose_name_plural': 'Планы развития',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HardwareInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.CharField(max_length=200, verbose_name='Значение/Характеристика')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Аппаратный интерфейс',
                'verbose_name_plural': 'Аппаратные интерфейсы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название модуля')),
                ('icon', models.CharField(choices=[('cpu', 'Процессор'), ('eye', 'Зрение/Трекинг'), ('crosshair', 'Наведение'), ('video', 'Видео/Стриминг'), ('settings', 'Настройки'), ('chip', 'Контроллер'), ('wifi', 'Связь'), ('terminal', 'Терминал')], default='cpu', max_length=50, verbose_name='Иконка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tech_details', models.TextField(blank=True, help_text='Например: "~20 fps при 4K-потоке"', verbose_name='Технические детали')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Модуль ПО',
                'verbose_name_plural': 'Модули ПО',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SoftwarePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(default='Программное обеспечение обеспечивает автоматическое сопровождение воздушных целей и наведение двухосевой турели.', verbose_name='Вводный текст')),
                ('platform_name', models.CharField(default='Android 12 AOSP', max_length=100, verbose_name='Платформа')),
                ('hardware', models.CharField(default='8-ядерный CPU, GPU Adreno', max_length=200, verbose_name='Бортовой вычислитель')),
                ('app_type', models.CharField(default='Монолитное Android-приложение (APK)', max_length=100, verbose_name='Тип приложения')),
                ('languages', models.CharField(default='Scala, Java, C++ (NDK)', max_length=200, verbose_name='Языки разработки')),
            ],
            options={
                'verbose_name': 'Платформа ПО',
                'verbose_name_plural': 'Платформа ПО',
            },
        ),
    ]
